### ISSUE TITLE
No Micro G 

### ISSUE THREAD

**Issue by 4adbfa76** [cawilliamson/treble_voltage#24] opened 2024-03-17 03:42 UTC
I flashed the recent build: VoltageOS-microg-arm32_binder64-ab-vndklite-3.2-20240316-UNOFFICIAL

There is no micro g, I search the whole system.

**Comment by cawilliamson** [comment] 2024-03-17 08:00
Yeah - I just heard a report of that. Looking in to it now!

**Comment by 4adbfa76** [comment] 2024-03-17 11:40
OK.

**Comment by Alien-Tec** [comment] 2024-03-24 14:08
Hello.

1. I can confirm, there is no MicroG option in the settings menu.

2. Further, Android Auto does not work with sandboxed Google. There is no option to configure it.
The car says connection failed.

3. BackUp doesn't work because Seedvault is missing.

Hope to see these problems fixed anytime soon.

Regards.

**Comment by inmaldrerah** [comment] 2024-03-26 02:17
I didn't find MicroG in the arm64 microg version (VoltageOS-microg-arm64-ab-3.2-20240316-UNOFFICIAL) either.

**Comment by Atman-5** [comment] 2024-03-28 10:56
There is none in the arm64 vndklite version either, supposing it's missing from all microg builds.

**Comment by cawilliamson** [comment] 2024-04-03 18:57
I've had a nightmare building the newer Voltage sources but am getting on top of it now. This will be addressed in the next build.

**Closed as completed by cawilliamson** 2024-04-03 18:57 UTC
